spring:
  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/achievement?useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
    username: root
    password: root
    initial-size: 10
    maximum-pool-size: 35
    test-while-idle: true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        #        添加可以访问的ip
        #        allow: 190.168.0.105
        #        正确登陆之后访问
        login-password: scoreInfo
        login-username: scoreInfo

  social:
    auto-connection-views: true

mybatis:
  type-aliases-package: com.achievement.entity
  mapper-locations: classpath*:mapper/*.xml
  check-config-location: true
  config-location: classpath:mybatis/mybatis-config.xml

achievement:
  delete:
    #    删除成绩
    score: false
  #    成绩管理系统首页
  indexUrl: http://www.baidu.com


